include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    # Error rules
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - empty_statements
    - hash_and_equals
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements

    # Style rules
    - always_declare_return_types
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures

    # Doc comments
    - package_api_docs
    - public_member_api_docs

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Treat missing required documentation as an error
    public_member_api_docs: error
    # Treat missing return types as an error
    always_declare_return_types: error
    # Treat passing nullable values to non-null variables as an error
    invalid_assignment: error
  exclude:
    - "lib/src/platforms/android/bindings.dart"
    - "build/**"
    - ".dart_tool/**"
