name: is_tv_ffi
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.14.2
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jnigen: ^0.14.2
  ffigen: ^19.1.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
