name: is_tv_ffi
description: "A Flutter plugin to detect if the current device is a TV"
version: 0.4.0
homepage: https://github.com/aumb/is_tv_ffi
repository: https://github.com/aumb/is_tv_ffi
issue_tracker: https://github.com/aumb/is_tv_ffi/issues
topics:
  - tv
  - ffi

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  jni: ^0.14.2
  mocktail: ^1.0.4
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jnigen: ^0.14.2
  ffigen: ^19.1.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      web:
        pluginClass: IsTvFfiWebPlugin
        fileName: src/platforms/web/bindings.dart
