// ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for Windows isTv check.
class IsTvFfiWindowsPlugin {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  IsTvFfiWindowsPlugin(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  IsTvFfiWindowsPlugin.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  bool is_tv() {
    return _is_tv();
  }

  late final _is_tvPtr = _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
    'is_tv',
  );
  late final _is_tv = _is_tvPtr.asFunction<bool Function()>();
}

const int __bool_true_false_are_defined = 1;

const int true$ = 1;

const int false$ = 0;
