// ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for the native isTv check shared by iOS, macOS, Linux and Windows.
class IsTvFfiNativePlugin {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  IsTvFfiNativePlugin(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  IsTvFfiNativePlugin.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  bool is_tv() {
    return _is_tv();
  }

  late final _is_tvPtr = _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
    'is_tv',
  );
  late final _is_tv = _is_tvPtr.asFunction<bool Function()>();
}
